// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV5ZZHUaCORIj_S9YcQENmksUZqjm9qJM',
    appId: '1:27599034902:web:bd7d8814fec53e77a3b337',
    messagingSenderId: '27599034902',
    projectId: 'wodaily-ed188',
    authDomain: 'wodaily-ed188.firebaseapp.com',
    storageBucket: 'wodaily-ed188.appspot.com',
    measurementId: 'G-F6M8CX6GXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-bc2fuxoLQgg2csm01h6KBNVLXpGaeq0',
    appId: '1:27599034902:android:2316fa26fb43d928a3b337',
    messagingSenderId: '27599034902',
    projectId: 'wodaily-ed188',
    storageBucket: 'wodaily-ed188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqp8jteArrGsOB2MmrIsZyiNkLuU1aUQg',
    appId: '1:27599034902:ios:6b1e8170fc2a6d6fa3b337',
    messagingSenderId: '27599034902',
    projectId: 'wodaily-ed188',
    storageBucket: 'wodaily-ed188.appspot.com',
    androidClientId: '27599034902-agbgo47cluu7t9ogi9r08ug3trltefku.apps.googleusercontent.com',
    iosClientId: '27599034902-6lr1rgs8nu8gulrkv34nchita1h3ng63.apps.googleusercontent.com',
    iosBundleId: 'wod',
  );
}
